services:
  oven-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: oven-frontend-dev:1.5.2
    hostname: oven-frontend-dev
    container_name: oven-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.development
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - ovendevelop-net

networks:
  ovendevelop-net:
    external: true
