
FROM node:22.15.0-alpine3.20 AS builder
WORKDIR /app


ENV NODE_ENV=development
ENV DOCKER_BUILD=true

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

RUN NODE_ENV=development npm run build


FROM node:22.15.0-alpine3.20

WORKDIR /app

ENV NODE_ENV=production

RUN npm install -g serve

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/.env /app/.env
COPY --from=builder /app/scripts/entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

EXPOSE 4173

CMD ["/app/entrypoint.sh"]