# Dockerfile for production build of a Vite application
# This Dockerfile uses a multi-stage build to create a lightweight production image
# that only contains the necessary files to run the application.
# The first stage builds the application using the Node.js image, and the second stage
# copies the built files to a new image based on the same Node.js image.
# The final image is smaller and more secure, as it does not include the build tools
# or source code.
FROM node:22.15.0-alpine3.20 AS builder
ENV NODE_ENV=development
ENV VITE_MODE=production
ENV DOCKER_BUILD=true
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run build

# Build production image
FROM node:22.15.0-alpine3.20
ENV NODE_ENV=production
ENV VITE_MODE=production
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/.env /app/.env
COPY --from=builder /app/scripts/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
EXPOSE 4173
CMD ["/app/entrypoint.sh"]